services:
  db-auto-backup:
    image: glennprays/dbeasebackup:latest
    container_name: dbeasebackup-container
    env_file:
      - .env
    volumes:
      - ./service-account-key.json:/service-account-key.json
    network_mode: host



  
